### ISSUE TITLE
Not publishing the source early?

### ISSUE THREAD

**Issue by Spaceghost** [airtame/AIRTAME-core#1]
I was curious to see if there's anything up that I could actually start hacking against and wrapping for other languages, but there's nothing here just yet it seems.

**Comment by DonOregano** [comment]
I asked about source code on the airtame forums:
http://forum.airtame.com/t/linux-users-guide/793/6

But still: +1!

**Comment by cadesalaberry** [comment]
:+1:

**Comment by apexo** [comment]
Please comply with the GPL and publish configuration files for the boot loader and the kernel and all associated scripts that are required to put together a working image.

**Comment by atiti** [comment]
Have you looked at the repos at github.com/airtame? Both bootloader and latest kernel tree are there, including configurations.

https://github.com/airtame/linux
https://github.com/airtame/u-boot-imx

**Comment by cweiske** [comment]
@atiti - this issue here was originally about the airtame dongle and client sources. Do you plan to open them?

**Comment by apexo** [comment]
@atiti Sorry for the noise, I was looking at the wrong branch …

**Comment by Spaceghost** [comment]
This issue is for the core, not the kernel or bootloader. Please reopen this until the core sources for *this* repo are answered for.
